### ISSUE TITLE
トランザクションタイムアウトとクエリタイムアウトのテスト方法の調査

### ISSUE THREAD

**Issue by kazuki43zoo** [kazuki43zoo/spring-tx-timeout#1]
Spring + MyBatis使用時における「トランザクションタイムアウト」「クエリタイムアウト」のテスト方法を調査してください。
### 参考サイト
- http://qiita.com/yoshidan/items/7ce240ead835d48ce2a1
- http://qiita.com/kazuki43zoo/items/1ac208a49c1d6ceeb0b8

**Comment by kazuki43zoo** [comment]
参考サイトに、

http://qiita.com/kazuki43zoo/items/1ac208a49c1d6ceeb0b8

を追加。

**Comment by ToshihiroTamura** [comment]
検証用プログラム構成

ServiceFacade(timeout = 10秒)
  |
  |___ Service1
  |　　   |
  |　　|______Repository1(insert, getAll)
  |
  |____Service2(timeout = 10秒)
　　　｜
　　　|______Repository1(insert, getAll)
　　　|
　　　｜______Repository2(insert, getAll, sleep20秒)
- トランザクションタイムアウト

Controllerが直接Service1を呼んだときタイムアウトは起こらない(getAllで情報が登録されたことを確認)
Controllerが直接Service2を呼んだとき
    Repository1.insert　→　Repository2.insert　→　sleep　タイムアウトは起こらない(getAllで情報が登録されたことを確認)
    Repository1.insert　→　sleep　→　Repository2.insert　タイムアウトは起こる(getAllで情報が登録されていないことを確認)
    sleep　→　Repository1.insert　→　Repository2.insert　タイムアウトは起こる(getAllで情報が登録されていないことを確認)

ControllerがServiceFacadeを呼んだときタイムアウトが起こる(getAllの結果、情報が登録されていないことを確認)

いずれもorg.springframework.transaction.TransactionTimedOutExceptionがスローされる

参考サイト：
http://stackoverflow.com/questions/7469661/how-jta-jts-handle-transaction-t‌​ime-out-issue
http://stackoverflow.com/questions/34496105/spring-transactional-timeout

わざと処理を止めてタイムアウトを発生させるためにThread.sleepを使っていたが、これだけでは例外がスローされず、タイムアウト後にサービスやリポジトリを呼び出すとエラーが発生する。
下のURLの例ではSELECT SLEEP()で止めていたが、これはMYSQLの機能でありH2にはない（H2のコンソールではできるっぽいがやりかたがわかってない）
- クエリタイムアウト

H2でテーブルロックやスリープを再現できれば、DB接続中にどんなエラーになるか検証可能だと思う……
- 補足

application.properties / .ymlでの設定値としてserver.session.timeoutという項目があるが、
ドキュメントによるとspring-boot-starter-redisを導入していないと効かないようだ
http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-session
そのほか非同期処理用のタイムアウト値：spring.mvc.async.request-timeoutやCOUCHBASE，CASSANDRAなどのシステム用のタイムアウト設定項目があるが、ORACLEやMYSQL用のものはない
Tomcat等のサーバアプリはサーバ側でもタイムアウトを設定できる

**Comment by ToshihiroTamura** [comment]
- クエリタイムアウト
  巨大なリストを挿入したところ、タイムアウトで設定した時間を超えるとTransactionTimedOutExceptionがスローされた。↑で挙げたリンクの回答では検知されないとあるが、投稿が古いためSpringのバージョンアップにより改善されたのかもしれない。

**Comment by kazuki43zoo** [comment]
スタックトレースはれる？

**Comment by ToshihiroTamura** [comment]
お待たせしてすいません(・_・;)
以下の方法でエラー内容の確認をしました。

トランザクションタイムアウト
- timeoutを10秒にし、10秒スリープをかけた後にデータをDB(H2)に登録する

クエリタイムアウト
- timeoutを1秒にし、100,000件のリストデータをDB(H2)に登録する

その結果、どちらも同じ↓のエラーが表示されました。

```
org.springframework.transaction.TransactionTimedOutException: Transaction timed out: deadline was Mon May 09 15:12:25 JST 2016
    at org.springframework.transaction.support.ResourceHolderSupport.checkTransactionTimeout(ResourceHolderSupport.java:141) ~[spring-tx-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.transaction.support.ResourceHolderSupport.getTimeToLiveInMillis(ResourceHolderSupport.java:130) ~[spring-tx-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.transaction.support.ResourceHolderSupport.getTimeToLiveInSeconds(ResourceHolderSupport.java:114) ~[spring-tx-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.mybatis.spring.transaction.SpringManagedTransaction.getTimeout(SpringManagedTransaction.java:139) ~[mybatis-spring-1.3.0.jar:1.3.0]
    at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85) ~[mybatis-3.4.0.jar:3.4.0]
    at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49) ~[mybatis-3.4.0.jar:3.4.0]
    at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.4.0.jar:3.4.0]
    at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.4.0.jar:3.4.0]
    at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) ~[mybatis-3.4.0.jar:3.4.0]
    at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185) ~[mybatis-3.4.0.jar:3.4.0]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434) ~[mybatis-spring-1.3.0.jar:1.3.0]
    at com.sun.proxy.$Proxy68.insert(Unknown Source) ~[na:na]
    at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:279) ~[mybatis-spring-1.3.0.jar:1.3.0]
    at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:56) ~[mybatis-3.4.0.jar:3.4.0]
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53) ~[mybatis-3.4.0.jar:3.4.0]
    at com.sun.proxy.$Proxy70.insertList(Unknown Source) ~[na:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at com.sun.proxy.$Proxy72.insertList(Unknown Source) ~[na:na]
    at com.example.domain.service.TodoService1.insertList(TodoService1.java:35) ~[classes/:na]
    at com.example.domain.service.TodoService1$$FastClassBySpringCGLIB$$d3981fb4.invoke(<generated>) ~[classes/:na]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655) ~[spring-aop-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at com.example.domain.service.TodoService1$$EnhancerBySpringCGLIB$$7b8a3b27.insertList(<generated>) ~[classes/:na]
    at com.example.api.TodoController.postListToService(TodoController.java:50) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:870) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844) ~[spring-webmvc-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_77]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_77]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at java.lang.Thread.run(Unknown Source) [na:1.8.0_77]
```

**Comment by kazuki43zoo** [comment]
なるほど・・・大量データ方式だとタイミング次第なので、テーブルロックなどでクエリ実行時にタイムアウトを迎えるようにしないとダメだね。
H2はGW中の暫定DBなので、Oracleでテーブルロックする方法を調べて試してください！

**Comment by ToshihiroTamura** [comment]
Oracleの場合、LOCK TABLEというSQLが用意されているので、それを使えば可能だと思います。
ロック後は、コミットやロールバックしない限り解除されないそうなので、ロック後スリープをかけて別のトランザクションからアクセスすればクエリタイムアウトを実現できそうです。

http://stackoverflow.com/questions/8570440/lock-table-in-oracle-database-using-jdbc-driver

ただし、MybatisのMapperに該当するものがないのでjavaファイル内にSQLを書くことになると思いますが。

**Comment by kazuki43zoo** [comment]
> ただし、MybatisのMapperに該当するものがないのでjavaファイル内にSQLを書くことになると思いますが。

`JdbTemplate`で経由でSQL実行してロックかな。

**Comment by ToshihiroTamura** [comment]
- 実環境でのトランザクションタイムアウト試験について

これまではService内で直接Thread.sleepを呼び出すことでタイムアウトを起こしていましたが、実環境ではそうはいかないので、テストコードの中に何らかの処理を行う必要があります。
そこでテストコード内でAOPを定義し、特定のメソッドを呼び出す前にThread.sleepを割り込ませることでタイムアウトを起こすことができました。
- 実環境でのクエリタイムアウト試験について

上のコメントの通り、LOCK TABLEというSQLでテーブルロックをかけることはできるのですが、ロックをかけるセッションと処理をするセッションが同じだとロックがかからないようです。別スレッドをたててロックをかけたりしてみましたが、ダメでした。なおSTSとSQL Developerはセッションが別なので、SQL Developer側でロックをかけた場合は、うまくいきます（プログラムがロックしたテーブルにアクセスすると待機状態になる）。

ちなみに、ロックをかけたまま１時間放置してみましたが何も起こらず、SQL Developer側でロックを解除するとTransactionTimedOutExceptionがスローされました。

テストを行うたびにSQL Developerでロックをかけるのは手間なのでプログラム側でセッションを変えられるとよいのですが。
